"""
routes/scoring.py — Lead Score Explanation Endpoint
===================================================
"""

import logging
from fastapi import APIRouter, HTTPException
from models import ScoreResponse
from scoring import get_score_explanation

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Scoring"])


@router.get("/leads/{lead_id}/score-explanation", response_model=ScoreResponse)
async def score_explanation(lead_id: str):
    """
    Get a lead's computed score (0-100) and an AI-generated explanation.
    
    The score is based on transparent, rule-based heuristics:
    - Priority weight, recency, source quality, contact status
    
    The explanation is generated by the Groq LLM in plain English.
    """
    try:
        result = await get_score_explanation(lead_id)
        return ScoreResponse(
            score=result["score"],
            explanation=result["explanation"],
        )
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error(f"[ERROR] Score explanation endpoint failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))
